# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'location-base-sharing-sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for location-base-sharing-sample

  target 'location-base-sharing-sampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end
	pod ‘GoogleMaps’
    pod 'GooglePlaces'
    pod 'Firebase/Core'
    pod 'Firebase/Database'

end
